# check all disruptions have correct format, then deploy to aws if check passes
name: Check and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Check disruptions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/requirements.txt
      - name: Check disruptions
        run: |
          python ./src/check.py

  # Only deploy if check passes and on push to main branch
  deploy:
    name: Deploy to AWS
    needs: [check]
    if: ${{ success() && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/requirements.txt
      - name: Create disruptions.json from disruptions folder
        run: |
          python ./src/create_json.py
      - name: Load disruptions.json into payload
        id: create_payload
        run: |
          content=`cat ./disruptions.json`
          echo "::set-output name=payload::$content"
      - name: Invoke AWS Lambda
        id: invoke_aws_lambda
        uses: gagoar/invoke-aws-lambda@master
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: ${{ secrets.AWS_REGION }}
          FunctionName: ttwCustomDisruptionCollector
          Payload: ${{ steps.create_payload.outputs.payload }}
      - name: AWS Lambda response success
        if: ${{ fromJSON(steps.invoke_aws_lambda.outputs.response).StatusCode == 200 }}
        run: |
          echo "AWS Lambda response ${{ steps.invoke_aws_lambda.outputs.response }} Success!"
      - name: AWS Lambda response failure
        if: ${{ fromJSON(steps.invoke_aws_lambda.outputs.response).StatusCode != 200 }}
        run: |
          echo "AWS Lambda response ${{ steps.invoke_aws_lambda.outputs.response }} Failure!"
          echo "Error: ${{ fromJSON(steps.invoke_aws_lambda.outputs.response).body }}"
          exit 1
